

<br class="long"/>

# Clustering/ Cell subset detection

<br>

For automated cell subset detection also called cell clustering, two methods are provided at the moment:

* FlowSOM 
* ClusterX
    
<br>

Both these methods perform unsupervised clustering, are fast and accurate when compared to other methods.

<br>

### FlowSOM
FlowSOM, analyzes Flow or mass cytometry data using a Self-Organizing Map. It uses two-level clustering and star charts, the algorithm helps to obtain a clear overview of how all markers are behaving on all cells, and to detect subsets that might be missed otherwise.

<br>

### ClusterX
ClusterX is a clustering method improved from Clustering by fast search and find of density peaks.It is a density-based clustering algorithms, which is applied to the t-SNE map. The first step is to perform t-SNE dimensionality reduction and then estimate local density on the t-SNE maps. The cluster centers are represented by the density peaks and it then assigns the remaining cells to clusters. 

<br>

### References
1. 
Van Gassen et al., FlowSOM: Using self-organizing maps for visualization and interpretation of cytometry data. Cytometry A. 2015 Jul;87(7):636-45 http://www.r-project.org, http://dambi.ugent.be.

2. Chen H et al.,  A Bioconductor Package for an Integrated Mass Cytometry Data Analysis Pipeline. PLoS Comput Biol 12(9): e1005112. https://doi.org/10.1371/journal.pcbi.1005112
